### PR TITLE
[fix] Dead Links

### PR DESCRIPTION
**Pull request by frju365**

### CODE REVIEW

**Comment by Psycojoker** [comment]
Why remove vagrant?

**Comment by frju365** [comment]
I didn't know, but I thought we had no more Vagrant Box prebuilt.

**Comment by Psycojoker** [comment]
We still have : unstable and stretch-unstable (if I remember correctly)

**Comment by Psycojoker** [comment]
(we have removed stable and testing because not one were using it and we didn't have that much disk space for it)

**Comment by frju365** [comment]
Well, stretch-unstable and unstable are the same now ?

**Comment by frju365** [comment]
Fixed.

**Comment by zamentur** [comment]
I think we should remove this page, because now we have this one: https://yunohost.org/#/images

**Comment by frju365** [comment]
yes.. perhaps keeping this page for the dev/test release ?

**Comment by alexAubin** [comment]
Alright guys, yesterday I worked on this and simply removed the whole index page and use autoindexing instead : https://build.yunohost.org/

I think the purpose of this repository should be reworked as a whole to include : 
- information / links to other repos we use to build our images, such as rpi-image, arm-images and cd_build
- the `update-images.py` script that is used to maintain the `images.json` file (itself being the interface to generate https://yunohost.org/#/images )

At some point, there was also a plan to merge this LXC with vinaigrette's one (forge2)

**Comment by alexAubin** [comment]
Closing (c.f. previous comment)

**Pull request closed without merging**
